/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-10-24 01:15:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\" dir=\"ltr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Home</title>\r\n");
      out.write("    <link rel=\"icon\" href=\"images/icon.jpg\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"fundo\">\r\n");
      out.write("    <div id=\"divBground\" class=\"bg\">\r\n");
      out.write("        <a href=\"login.jsp\" class=\"txtLogin btnLog\">Login</a>\r\n");
      out.write("        <h2 class=\"text-center logo\">TFIN</h2>\r\n");
      out.write("        <h5 class=\"text-center\">The Future is Now</h5>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"divCabecalho-nav\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("            <div id=\"navbarNavAltMarkup\">\r\n");
      out.write("                <div class=\"navbar-nav\">\r\n");
      out.write("                    <div class=\"col-md-3\"><a class=\"nav-item nav-link active\" href=\"index.jsp\">Home</a></div>\r\n");
      out.write("                    <div class=\"col-md-3\"><a class=\"nav-item nav-link active\" href=\"cursos.jsp\">Cursos</a></div>\r\n");
      out.write("                    <div class=\"col-md-3\"><a class=\"nav-item nav-link active\" href=\"ajuda.jsp\">Contato</a></div>\r\n");
      out.write("                    <div class=\"col-md-3\"><a class=\"nav-item nav-link active\" href=\"quemSomos.jsp\">Sobre o Chat</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container my-3\">\r\n");
      out.write("            <div class=\"principal-card text-center col-12 col-sm-12 col-md-12 col-lg-12 border border-dark rounded divsindex\">\r\n");
      out.write("                <h2 class=\"card-title tlIndex\">Tem Dúvidas em Matemática?</h2>\r\n");
      out.write("                <div class=\"card-body cbDuvidas\">\r\n");
      out.write("                    <p class=\"card-text\">Rodriguinho tem as as respostas que você precisa!</p>\r\n");
      out.write("                    <a href=\"quemSomos.jsp\" class=\"btn corbotao\">Conheça o nosso Bot</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <section class=\"row my-4\">\r\n");
      out.write("            <div class=\"col-12 col-sm-12 col-md-6 col-lg-4 my-1\">\r\n");
      out.write("                <div class=\"principal-card border border-dark\">\r\n");
      out.write("                    <img src=\"./images/math.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    <div class=\"card-body cbIndex border-top border-dark\">\r\n");
      out.write("                    <h5 class=\"card-title ctIndex\">Você sabe o que é Função?</h5>\r\n");
      out.write("                    <p class=\"card-text\">Toda vez que temos dois conjuntos e algum tipo de associação entre eles, que faça corresponder a todo elemento do primeiro conjunto um único elemento do segundo, ocorre uma função.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-12 col-sm-12 col-md-6 col-lg-4 my-1\">\r\n");
      out.write("                <div class=\"principal-card border border-dark\">\r\n");
      out.write("                    <img src=\"./images/brinquedo.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    <div class=\"card-body cbIndex border-top border-dark\">\r\n");
      out.write("                    <h5 class=\"card-title ctIndex\">Você sabe o que são Derivadas?</h5>\r\n");
      out.write("                    <p class=\"card-text\">No cálculo, a derivada em um ponto de uma função representa a taxa de variação instantânea em sua relação neste ponto. Um exemplo típico é a função velocidade que representa a taxa de variação do espaço.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-12 col-sm-12 col-md-6 col-lg-4 my-1\">\r\n");
      out.write("                <div class=\"principal-card border border-dark\">\r\n");
      out.write("                    <img src=\"./images/graficos.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    <div class=\"card-body cbIndex border-top border-dark\">\r\n");
      out.write("                    <h5 class=\"card-title ctIndex\">Você sabe o que são Integrais?</h5>\r\n");
      out.write("                    <p class=\"card-text\">No cálculo, a integral de uma função foi criada originalmente para determinar a área sob uma curva no plano cartesiano. ela também surge naturalmente em dezenas de problemas da física.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"page-footer font-small blue ftGeral\">\r\n");
      out.write("    <div class=\"footer-copyright text-center py-3\">© 2019 Copyright:\r\n");
      out.write("        <a href=\"index.jsp\">RodriguinhoBot</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
